.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Matt Tytel <matthewtytel@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HELM SECTION "Mai  8, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOM
helm \- un programme pour faire de la musique
.SH SYNOPSIS
.B helm
.RI [ options ] " fichiers" ...
.br
.B bar
.RI [ options ] " fichiers" ...
.SH DESCRIPTION
Cette page de manuel documente brièvement la commande helm.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBhelm\fP est un programme qui fait du son à l'aide de synthèse
.SH OPTIONS
Ces programmes suivent la syntaxe GNU habituelle de ligne de commande, avec 
les options longues commençant avec deux tirets (`-').
Un résumé des options est intégré ci-dessous.
Pour une description complète, voir les fichiers Info.
.TP
.B \-h, \-\-help
Affiche le sommaire des options.
.TP
.B \-v, \-\-version
Affiche la version du programme.
.br
Boooooooop beeeeeeep
